### ISSUE TITLE
Outdated dictionary?

### ISSUE THREAD

**Issue by 3asy** [LeonR/vzWordyHoster#1]
Love the hoser, hate the dictionary!

**Comment by LeonR** [comment]
Well, you don't have to use the dictionary that I use. The hoster just needs any dictionary in an XML format whose structure I haven't got around to documenting yet, but which you can see in the examples in the Debug folder. Also, the hoster can host DD in infinite mode (as you've been observing) or finite mode, in which the host prepares a set of words/definitions and runs through all of them.

Having said that, I think infinite mode is great because it requires zero effort on the part of the host, and yet provides an engaging game. So find me a better open-source dictionary in text format, CSV, XML or something similar, and I'll convert it!

**Comment by LeonR** [comment]
Having thought about this and having consulted others who have played the game, I have no intention of providing a full dictionary with the hoster. There are two main reasons for that:

1) The dictionary is in XML format, which can be opened in any text editor or web browser. Any avatar could download the dictionary, search for the dictionary definition read out by the host, and instantly find the answer.

2) Devil's Dictionary in Infinite mode is generally just too hard anyway. Any game in DS/NH would probably require a prepared word file (to be used in DD Finite mode) for the game to be viable.

On those grounds I am closing the issue.
